### ISSUE TITLE
Notification 表示時に 4.2.2 端末で強制終了

### ISSUE THREAD

**Issue by mag0716** [mag0716/android_periodic_execution#37]
## Description

```
07-11 23:28:41.051 11753-11753/com.github.mag0716.memorytraining E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   android.app.RemoteServiceException: Bad notification posted from package com.github.mag0716.memorytraining: Couldn't create icon: StatusBarIcon(pkg=com.github.mag0716.memorytraininguser=0 id=0x7f070077 level=0 visible=true num=0 )
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                       at android.os.Looper.loop(Looper.java:213)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5092)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
```

対象 OS バージョンではないが、念のため調べておく。

**Comment by mag0716** [comment]
vector 画像を利用しているから

https://stackoverflow.com/questions/34016107/can-we-use-vectordrawable-or-vectorxml-as-icons-for-push-notifications-in-androi
